source $VIMRUNTIME/defaults.vim

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

colorscheme darcula

set novb
set noerrorbells
set bs=2
set magic
set incsearch
set hlsearch
set showmode
set showmatch
set laststatus=2
set expandtab
set tabstop=4
set shiftwidth=4
set smartindent
set list
set listchars=tab:»·,trail:·

map  :b#<CR>

autocmd BufWritePost ~/Work/journal/*.md execute '!git add % && git commit -m %:t'
